### PR TITLE
fix static build with readline

### PR DESCRIPTION
**Pull request by ffontaine**
Use pkg-config to get readline dependencies such as ncurses

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by nhorman** [comment]
It looks like an ok change for the most part, but the ci checks failed on it.  Im not sure why, as readline-dev is already pulled in, but if you can figure that out and fix it, I'll pull this

**Comment by ffontaine** [comment]
I updated the commit to keep current behavior as a fallback as readline.pc was added only in version 8 which is not widely deployed.

**Comment by nhorman** [comment]
ok, but the build is failing in CI, you need to fix that

**Comment by ffontaine** [comment]
What is failing in CI is make check -C tests (including on current master without my PR):
```
make  check-TESTS
make[2]: Entering directory `/home/travis/build/nhorman/dropwatch/tests'
make[3]: Entering directory `/home/travis/build/nhorman/dropwatch/tests'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
Build hangs because it starts rundropwatch.sh in CI since c9ff0fc856c067603d8b6865aca52ef20774be32 but you didn't set any timer so it runs forever ...

**Comment by nhorman** [comment]
dang, you're right, it looks like something in the CI environment has changed.  I wonder if we don't have network access anymore leading to a lack of drops....I'll see if I can fix it

**Comment by nhorman** [comment]
ok, its fixed.  Looks like the container network config changed for CI and we're not seeing any expected drops anymore, so the test hangs.  i've updated the test to time out in that case.  If you could please rebase this test so we get  a clean ci run, I'll merge it

**Pull request merged**
