### PR TITLE
codespell

### PR DESCRIPTION
**Pull request by onlyjob**
Spellcheck corrections.

### CODE REVIEW

**Comment by nhorman** [comment]
Thanks for the typo fixes, but please add a changelog here

**Comment by onlyjob** [comment]
Sorry I don't quite follow... A changelog??

**Comment by nhorman** [comment]
yes, when you commit the change in the local tree, you have the option to add a description of the changes, you added nothing.

**Comment by onlyjob** [comment]
You mean description of the pull request?

**Comment by nhorman** [comment]
No, I mean the changelog in the commit.  run git show master on the local tree where you made these changes and you will see no description of the change.  You need to add one there

**Comment by onlyjob** [comment]
There is a description - it is just one word "codespell" (arguably could be improved by making commit message longer and more descriptive) but it is certainly not nothing. Git would not even let you commit with an empty message.
Why "codespell" is not good enough? By the way this is the name of the tool that I have used to correct spelling mistakes.

**Comment by nhorman** [comment]
because 'codespell' is completely meaningless as a changelog entry.  Look at any/every other commit message in the history of the project, at a minimum it needs to indicate that this commit  indicating that you are cleaning up typos.  Just entering 'codespell' is unacceptable.

Also (not that this has any relevance), but since you mentioned it, you can create commits with empty changelog messages.  See the --allow-empty and --allow-empty-message in the git-commit man page.  But changelogs are meant to be descriptive entries that give you an overview of what the change is about, without having to glean that from the changes themselves, and 'codespell' doesn't hit that bar.

**Comment by onlyjob** [comment]
"Unacceptable"?? I've never thought I'd say this but you've won. You are more pedantic than I am.
I'm correcting spelling in comments and you are nitpicking on my commit message... :(

This is unworthy of further discussion. It should have taken few minutes at most and it already took too long. Take it or throw it away. Change commit message as you like. Whatever. I don't think I care enough to go back and forth over commit message...

**Comment by nhorman** [comment]
very well

**Comment by onlyjob** [comment]
Committed as dca5a6a184 (without attribution).

**Pull request closed without merging**
